### ISSUE TITLE
Negative expiration time

### ISSUE THREAD

**Issue by z3rone** [trustedsec/SHIPS#13]
In the backend I see a device with the expiration time 'About -3 days'. I recently set the expiration time of that device to one day, if that could be the cause for the problem...

**Comment by GeoffWalton** [comment]
The expiration time is ‘advisory’ to the client.  The server really has no way to make it do anything obviously.  What probably has happened is you set the expiration time to a smaller value than what was previously sent to the client.  The client is still waiting for the old expire time to arrive before it checks in.  In the mean time the server is reporting the expiration time and subtracting the last time it actually communicated with the client and as result is reporting a negative value.

if you have access to the client you could  modify the date in the password_history.txt file which would cause it to check in.  Otherwise I would expect the problem to resolve itself once the client checks in at the previously configured time.

Geoff Walton | Senior Security Consultant
CISSP
TRUSTEDSEC, LLC
C: 440.344.8967
Office: 877.550.4728
E: GEOFF.WALTON@TRUSTEDSEC.COM
https://www.trustedsec.com<https://www.trustedsec.com/>

YOUR TRUSTED SOURCE FOR INFORMATION SECURITY
