### ISSUE TITLE
Bruteforce safeguard ideas...

### ISSUE THREAD

**Issue by JDogHerman** [trustedsec/SHIPS#2]
Mind you that I haven't dived into the code yet but... It might be nice to have the web server, upon failure of a nonce verification, engage a predefined chosen task...
~place the IP on a block though the firewall for a "cool off" period (if the IP is local)
~notify the security team when a failure occurs
~run other predefined action

**Comment by trustedsec** [comment]
Brute forcing would be handled at the LDAP level with active directory integration and handled by traditional group policy. Since they are defined based on groups inside of AD - normal account lockout and detection capabilities would occur. When it comes to the SQL integration, we can look into that at a future date as a milestone. Appreciate the recommendations!

**Comment by JDogHerman** [comment]
Is the LDAP setup to authenticate hosts also or just users?
